### ISSUE TITLE
Mirrir Requests

### ISSUE THREAD

**Issue by lovelyzzc** [CQUPTMirror/Report#15]
Anaconda

Anaconda 作为python最好并且使用最为广泛的数据科学工具，越来越多的人使用，为了便于管理python环境，安装深度学习库，使用jupyter lab和jupyter notebook。

真的很想学校能够添加anacondda的镜像。

清华源
https://mirrors.tuna.tsinghua.edu.cn/anaconda/

**Comment by lovelyzzc** [comment]
希望能让重邮学子不再受conda install 的网速困扰

**Comment by Hisssy** [comment]
在同步了，过几天看看。

**Comment by lpengc** [comment]
请问现在anaconda同步了吗？使用红岩镜像时依然无法利用conda创建新环境

**Comment by Sajotim** [comment]
> 请问现在anaconda同步了吗？使用红岩镜像时依然无法利用conda创建新环境

我们这边测试没有出现问题，请提供一下具体报错信息。

**Comment by lpengc** [comment]
`**@**-desktop:~$ conda create -n tf python=3.6
Fetching package metadata .....

CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4bd57a6320>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)


**@**-desktop:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /data/**/programs/anaconda3  (writable)
    default environment : /data/**/programs/anaconda3
       envs directories : /data/**/programs/anaconda3/envs
          package cache : /data/**/programs/anaconda3/pkgs
           channel URLs : https://mirror.cqupt.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirror.cqupt.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/**/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-184-generic debian/stretch/sid glibc/2.23
                UID:GID : 1011:1011
`

**Comment by tangger2000** [comment]
@lpengc 你好，你这个问题应该由于conda镜像源顺序造成的。麻烦你根据以下教程，修改conda配置文件，然后再尝试一下，谢谢！



Windows 用户无法直接创建名为 `.condarc` 的文件（Linux在~/目录下没有该文件也一样），可先执行 `conda config --set show_channel_urls yes` 会生成该文件，然后将以下内容填入该文件内。

```
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.cqupt.edu.cn/anaconda
default_channels:
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/main
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/free
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/r
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/pro
  - https://mirrors.cqupt.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.cqupt.edu.cn/anaconda/cloud
  msys2: https://mirrors.cqupt.edu.cn/anaconda/cloud
  bioconda: https://mirrors.cqupt.edu.cn/anaconda/cloud
  menpo: https://mirrors.cqupt.edu.cn/anaconda/cloud
  pytorch: https://mirrors.cqupt.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.cqupt.edu.cn/anaconda/cloud

```

即可添加 Anaconda Python 免费仓库。

运行 `conda clean -i` 清除索引缓存，保证用的是镜像站提供的索引。

运行 `conda create -n myenv python=3.7` 测试一下吧。

测试成功以后，您就可以先用`conda search xxx`来查找包或者库是否存在以及版本号，然后使用`conda install xxx=???`来安装啦。

eg：

conda search tensorflow-gpu

conda install tensorflow-gpu=2.1.0
